version: '3'
services:
  registry:
    build: .
    ports:
     - "18080:18080"
    environment:
     - LOG_LEVEL=INFO
     - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/database
     - NIFI_REGISTRY_FLOW_PROVIDER=file
     - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/flow_storage
    volumes:
     - ./database:/opt/nifi-registry/database
     - ./flow_storage:/opt/nifi-registry/flow_storage
